### ISSUE TITLE
schemas: enrich JSON schema to allow specifying Gherkin feature files

### ISSUE THREAD

**Issue by audrium** [reanahub/reana-server#597]
Add a support to specify Gherkin feature files inside the `reana.yaml` specification. 
Example:
```yaml
...
tests:
  files:
    - tests/roofit.feature
    - tests/yadage.feature
...
```

**Comment by tiborsimko** [comment]
If we allow to specify more files here, then we could group the feature tests together around the same topic, for example:

```yaml
tests:
  files:
    - tests/workspace-files.feature
    - tests/log-messages.feature
    - tests/runtime-duration.feature
```

In the first test file, we would test everything workspace file presence, file checksum, file content, etc.

In the second test file, we would test everything about logs and outputs.

In the third test file, we would test workflow and job running times.

This might be nicer that having only one single feature file for the whole example:

```yaml
tests:
  files:
    - tests/root6-roofit.feature
```

which may look a bit cryptic since less explicit than the prior option.
